# Generated by Django 3.2.6 on 2021-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code_url',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='origin_url',
            field=models.URLField(),
        ),
    ]
